# Call this whatever you want
name: autoupdate

# When does it get run?
on:
  # workflow_dispatch means "I can click a button and force it to run"
  workflow_dispatch:
  # schedule/cron means "on a set schedule"
  schedule:
    - cron: "0 1 * * *"
jobs:
  scrape:
    # For some reason, we run love versions of linux
    runs-on: ubuntu-latest
    steps:
      # Download all of the code from your repo
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install necessary python packages
        run: |
            python -m pip install --upgrade pip
            pip install requests beautifulsoup4 pandas datetime nbconvert lxml

      - name: Convert notebook to Python script
        run: jupyter nbconvert --to script scrape_heroku.ipynb

      - name: Run the converted Python script
        run: python scrape_heroku.py

      # I just stole the rest of this code so don't ask me questions about it
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@user.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || echo "No changes to commit"
          git push || echo "nothing to push"